language: node_js
node_js: node

install:
  - yarn
script:
  - yarn run build
after_script:
  - echo "built"
  - ls -al

deploy:
  provider: pages
  fqdn: royniladri.dev
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  on:
    branch: master